language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sky-sharma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sky-sharma/docker-react npm run test -- --coverage
